### PR TITLE
Paella: Updated vendor to Nougat

### PR DESCRIPTION
**Pull request by Darkmet98**
(originally updated by @dimusa6 )

### CODE REVIEW

**Comment by marado** [comment]
Where's the companion device/bq/paella from which this was generated?

**Comment by Darkmet98** [comment]
what? I don't understand, sorry.

**Comment by marado** [comment]
Were this changes made manually, or is an updated https://github.com/LineageOS/android_device_bq_paella/blob/cm-14.1/setup-makefiles.sh somewhere?

**Comment by Darkmet98** [comment]
@marado my teammate @dimusa6 made this changes manually, but the script need some changes.
Anyway, tomorrow I going to upload the all changes with gerrit to lineageOS with all updated.

**Pull request closed without merging**
