### PR TITLE
paella: Add missing blob: libarcsoft_panorama_burstcapture.so

### PR DESCRIPTION
**Pull request by stucki**
Copied from piccolo

### CODE REVIEW

**Comment by marado** [comment]
This isn't used on paella (check [here](https://github.com/CyanogenMod/android_device_bq_paella/blob/cm-13.0/proprietary-files-qc.txt)), and bq seems to use it only for bq's camera, which we don't ship on CM.
In other words, this blob seems to be unnecessary for CM/paella.

**Comment by stucki** [comment]
The situation is 1:1 the same for piccolo. There is an (unofficial) zip available which adds the BQ camera to CyanogenMod. It is known to work for Paella too if this file is added here.

If you think it's wrong then we should probably delete the file from piccolo and vegetalte too (and add it to the BQ camera zip file instead).

You can find CameraBQ_signed_v4.1.0.zip at https://s.basketbuild.com/devs/eloimuns/bq/piccolo/

**Comment by marado** [comment]
Oh, I see.
Well, yes, if this is a blob that is needed for an app, and that app is distributed on a .zip, I'd guess the proper place for the blob to be would be in the zip.

**Comment by stucki** [comment]
I will check this. I'm not sure why the files are shipped for piccolo and vegetalte. If there's any other reason other than this camera zip file, then it will most likely be the same situation for paella.
If not, then I agree, the file can be removed from all three device trees (and be moved into the camera zip file).

Will leave this open until we have clarified it...

**Comment by stucki** [comment]
No longer needed (the file has been merged during the switch from paella to picmt codebase).

**Pull request closed without merging**
