### PR TITLE
piccolo : Update blobs for lineage-15.1 release.

### PR DESCRIPTION
**Pull request by eloimuns**
PINNED BLOBS:
libcneapiclient.so from 4.8.1 release.

sed -i "s|/system/etc|/vendor/etc|g" vendor/lib/libdsi_netctrl.so
sed -i 's|/system/build.prop|/vendor/etc/hdrhax|g' vendor/lib/libmmcamera_imglib.so
sed -i 's|/system/etc|/vendor/etc|g' vendor/bin/netmgrd
sed -i 's|/system/etc|/vendor/etc|g' vendor/bin/qmuxd
sed -i 's|/system/etc|/vendor/etc|g' vendor/bin/thermal-engine
sed -i 's|/system/etc|/vendor/etc|g' vendor/bin/wcnss_service

Change-Id: I69ae04a9b59a850690ed12398d71fd6576dc3628

### CODE REVIEW

**Comment by DaniPhii** [comment]
I'm still waiting for this pull request to be merged… 👀

**Comment by stucki** [comment]
@eloimuns This seems to work fine. Can you merge it?

**Comment by stucki** [comment]
@eloimuns Thank you!

**Comment by DaniPhii** [comment]
Thanks @eloimuns! 🙂

**Pull request merged**
